# Generated by Django 4.0.5 on 2024-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('facility_name', models.CharField(max_length=255)),
                ('district_id', models.PositiveIntegerField()),
                ('owner_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
